backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: blog
    label: Blogposts
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Datum, name: date, widget: datetime }
      - { label: Omschrijving, name: description, widget: text }
      - { label: Inhoud, name: body, widget: markdown }